services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_USER=new_user
      - MYSQL_PASSWORD=my_pwd
    ports:
      - 3306:3306  
    networks:
      - app-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9000:9000
    environment:
      - DB_SERVER=db
      - DB_PORT=3306
      - DB_DATABASE=api
      - DB_USER=root
      - DB_PASSWORD=root_pwd
    networks:
      - app-networks

networks:
  app-networks: