name: Continuous Integration

on: 
  push:
    branches:
      - feature/**
# aaa
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build da Aplicacao
        run: mvn clean package  
      